# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ebee9fd0c1faf688bdeff6ebfadf367976334b3693c6b91711f9a3660f35f2bc657411bfd7ab4283769e9bcfb0df6cc5d4d81d4de5e60f93ac7e5802c51c0e6

test:
  secret_key_base: 338b1eeb73e1f82d4d3b2439dbf19eba14feb7b7985d77be2a3eed8aa8fbaef9c3de724b32bce14161ac89219b4ce56901bca38916760f618ad3ffef2c089b61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
